"""
Architecture Agent — generates an architecture document: a dependency
diagram plus a narrative description of the repository's structure.

The Mermaid diagram itself is built deterministically from
`state.dependency_graph`, never generated by the LLM. Asking a model to
emit Mermaid syntax from scratch is a real, avoidable risk — a single
malformed edge or an unescaped character breaks the whole diagram, and
there's no way to validate Mermaid syntax without a renderer. Since the
diagram's actual content (which files import which) is already fully
known, deterministic generation is strictly more reliable here: the
LLM's job is narrowed to what LLMs are actually good at — describing
what the structure means — not reproducing structure it could get
wrong.

File selection and diagram rendering are deliberately separate pure
functions (`select_central_files`, `build_dependency_diagram`) rather
than one combined step — selection needs `max_nodes` and ranking logic,
rendering just needs an already-decided file list, and keeping them
apart makes each independently testable.

Selected files are ranked by total degree (dependents + dependencies),
the same "architectural centrality" reasoning the Repository Agent uses
for its file digest — a hub file with many connections is more useful
to show than a leaf file with none, when not everything fits in one
diagram.
"""

from __future__ import annotations

from dataclasses import dataclass

from config.prompts import render_prompt
from config.providers import resolve_synthesis_provider_config
from config.settings import get_settings
from graph.dependency import DependencyGraph
from graph.state import RepositoryState
from llm.base import BaseProvider, ChatMessage, ProviderError, Role
from llm.factory import create_provider
from utils.banned_phrases import find_banned_phrases, render_banned_phrase_findings
from utils.helpers import with_retry
from utils.logger import get_logger
from utils.timers import Stopwatch

log = get_logger(__name__)


@dataclass
class ArchitectureDigest:
    file_paths: list[str]
    diagram: str
    """Mermaid `flowchart` syntax, built deterministically."""
    file_digest: str
    """One-line-per-file summaries for the selected files, same rendering as the Repository Agent's digest."""


async def architecture_node(state: RepositoryState) -> dict[str, object]:
    """LangGraph node: generate `state.generated_docs["architecture"]`."""
    all_files = sorted(state.parse_results.keys())
    if not all_files:
        return {"generated_docs": state.generated_docs, "statistics": state.statistics, "errors": state.errors}

    max_nodes = get_settings().architecture_max_nodes
    selected = select_central_files(state.dependency_graph, all_files, max_nodes=max_nodes)
    diagram = build_dependency_diagram(selected, state.dependency_graph)
    file_digest = _render_file_digest(selected, state)
    digest = ArchitectureDigest(file_paths=selected, diagram=diagram, file_digest=file_digest)

    config = resolve_synthesis_provider_config()

    with Stopwatch("architecture") as sw:
        async with create_provider(config) as provider:
            try:
                narrative, prompt_tokens, completion_tokens = await generate_architecture_narrative(digest, state.repo_summary, provider)
            except ProviderError as exc:
                state.record_error("architecture", f"Failed to generate architecture narrative: {exc}", exception=exc)
                return {"generated_docs": state.generated_docs, "statistics": state.statistics, "errors": state.errors}

            tokens_used = (prompt_tokens or 0) + (completion_tokens or 0)

            # Deterministic scan, same detector README uses — a "don't say X"
            # prompt instruction alone has proven unreliable across repeated
            # real runs, so this is a substring match that can't be talked
            # out of flagging a hit. The narrative is short (3-6 sentences),
            # so a single fix pass is cheap; no need for README's full loop.
            phrase_hits = find_banned_phrases(narrative)
            if phrase_hits:
                log.info("Architecture Agent: deterministic scan caught %d banned-phrase hit(s): %s", len(phrase_hits), phrase_hits)
                fix_prompt = render_prompt(
                    "architecture_revise", draft=narrative, findings=render_banned_phrase_findings(phrase_hits)
                )
                messages = [ChatMessage(role=Role.USER, content=fix_prompt)]
                try:
                    async for attempt in with_retry(max_attempts=3, exceptions=(ProviderError,)):
                        with attempt:
                            fix_result = await provider.generate(messages, temperature=0.1, max_tokens=500)
                    narrative = fix_result.text.strip()
                    tokens_used += (fix_result.prompt_tokens or 0) + (fix_result.completion_tokens or 0)
                except ProviderError as exc:
                    log.info("Architecture Agent: banned-phrase fix pass failed (%s), keeping unfixed narrative", exc)

    state.statistics.tokens_used += tokens_used
    doc = f"{narrative}\n\n```mermaid\n{digest.diagram}\n```\n"
    state.generated_docs["architecture"] = doc

    log.info("Architecture Agent: document generated (%d diagram node(s)) in %.2fs", len(selected), sw.elapsed_seconds)

    return {"generated_docs": state.generated_docs, "statistics": state.statistics, "errors": state.errors}


def select_central_files(dependency_graph: DependencyGraph, all_files: list[str], *, max_nodes: int) -> list[str]:
    """
    Rank `all_files` by total degree (dependents + dependencies) and
    return the top `max_nodes`, alphabetically sorted for stable,
    readable output. Returns all files, alphabetically, if under the cap.
    """
    if len(all_files) <= max_nodes:
        return sorted(all_files)

    def degree(path: str) -> int:
        return len(dependency_graph.dependents_of(path)) + len(dependency_graph.dependencies_of(path))

    return sorted(sorted(all_files, key=degree, reverse=True)[:max_nodes])


def build_dependency_diagram(file_paths: list[str], dependency_graph: DependencyGraph) -> str:
    """Build a Mermaid `flowchart TD` over exactly `file_paths`, including only import edges between them."""
    id_map = {path: f"n{i}" for i, path in enumerate(file_paths)}

    lines = ["flowchart TD"]
    for path, node_id in id_map.items():
        safe_label = path.replace('"', "'")
        lines.append(f'    {node_id}["{safe_label}"]')

    selected_set = set(file_paths)
    seen_edges: set[tuple[str, str]] = set()
    for edge in dependency_graph.internal_edges():
        if edge.source not in selected_set:
            continue
        for target in edge.targets:
            if target not in selected_set or (edge.source, target) in seen_edges:
                continue
            seen_edges.add((edge.source, target))
            lines.append(f"    {id_map[edge.source]} --> {id_map[target]}")

    return "\n".join(lines)


def _render_file_digest(file_paths: list[str], state: RepositoryState) -> str:
    lines = []
    for path in file_paths:
        doc = state.file_docs.by_path(path)
        summary = doc.summary if doc is not None and doc.error is None else "(not documented)"
        lines.append(f"- {path}: {summary}")
    return "\n".join(lines)


async def generate_architecture_narrative(
    digest: ArchitectureDigest, repo_summary: str | None, provider: BaseProvider
) -> tuple[str, int | None, int | None]:
    """Generate the prose narrative accompanying `digest.diagram`. Raises `ProviderError` after retries are exhausted."""
    prompt = render_prompt(
        "architecture",
        repo_summary=repo_summary or "(not yet established)",
        file_count=len(digest.file_paths),
        file_digest=digest.file_digest,
    )
    messages = [ChatMessage(role=Role.USER, content=prompt)]

    async for attempt in with_retry(max_attempts=3, exceptions=(ProviderError,)):
        with attempt:
            result = await provider.generate(messages, temperature=0.1, max_tokens=500)

    return result.text.strip(), result.prompt_tokens, result.completion_tokens
